version: '3.8'

services:
  maamoura-hotel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maamoura-hotel-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
